### ISSUE TITLE
Nothing plays

### ISSUE THREAD

**Issue by ronilaukkarinen** [dirkgroenen/mopidy-mopify#132]
Sorry if I posted to the wrong section, but I just started using Mopidy and nothing plays in Mopify when I click the play button.

````
[00:55:25] [66.0 C] rolle ~ $ mopidy
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO     Starting Mopidy 1.1.0
INFO     Loading config from builtin defaults
INFO     Loading config from /home/rolle/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, mpd, http, moped, stream, m3u, softwaremixer, file, local
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Loaded 0 M3U playlists from /home/rolle/.local/share/mopidy/m3u
INFO     Audio output set to "autoaudiosink"
WARNING  Failed expanding path ($XDG_MUSIC_DIR) fromfile/media_dirs config value.
INFO     Loaded 19877 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: QueueManagerFrontend, MpdFrontend, HttpFrontend
INFO     MPD server running at [::]:6600
INFO     HTTP server running at [::ffff:192.168.2.100]:6680
````

/home/rolle/.config/mopidy/mopidy.conf
````
[local]
enabled = true
library = json
media_dir = /media/giant/levyt
data_dir = /home/rolle/mopidy/data
playlists_dir = /home/rolle/mopidy/playlists
scan_timeout = 1000
scan_flush_threshold = 1000
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt

[mpd]
hostname = ::

[http]
enabled = true
hostname = 192.168.2.100
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname

[spotify]
username = XXXXXX
password = XXXXXX

[subsonic]
hostname = 192.168.2.100
port = 4040
username = XXXXXX
password = XXXXXX
ssl = no

[mopify]
enabled = true
debug = false

[stream]
enabled = true
protocols =
    http
    https
    mms
    rtmp
    rtmps
    rtsp
timeout = 5000
````

Chrome console:
````
WARNING: Tried to load angular more than once.
mopidy-mopify-1.5.7.js:33 Potentially unhandled rejection [1] TypeError: Cannot read property 'uri' of undefined
    at http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:23:15866
    at P (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:11025)
    at L (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:10657)
    at z.when (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:14301)
    at w.run (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:13337)
    at a._drain (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:32:30708)
    at drain (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:32:30362)
    at http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:32:29459(anonymous function) @ mopidy-mopify-1.5.7.js:33
mopidy-mopify-1.5.7.js:33 Potentially unhandled rejection [2] TypeError: Cannot read property 'uri' of undefined
    at http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:23:15866
    at P (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:11025)
    at L (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:10657)
    at z.when (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:14301)
    at w.run (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:33:13337)
    at a._drain (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:32:30708)
    at drain (http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:32:30362)
    at http://192.168.2.100:6680/mopify/assets/mopidy-mopify-1.5.7.js:32:29459(anonymous function) @ mopidy-mopify-1.5.7.js:33
mopidy-mopify-1.5.7.js:12 SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
````

Using Fedora Server 22.
Any tips?

**Comment by dirkgroenen** [comment]
Could you enable debug in the Mopidy configuration? 
```
[mopify]
enabled = true
debug = true
```

This doesn't ring a bell at the moment so a bit more information could help much.

**Comment by ronilaukkarinen** [comment]
Enabled it now, but doesn't help much. Also, not seeing local files, only Spotify stuff. Nothing seems to happen when I press play button.

![screenshot](http://i.imgur.com/FhfKtwu.jpg "screenshot")
![screenshot](http://i.imgur.com/DoqP3e2.png "screenshot")

**Comment by dirkgroenen** [comment]
The mopify `debug` option loads the unminified files. Can you please show the errors in your browser's console with the `debug` option set to `true`?

As for your other issue with the client only showing the Spotify tracks: this is expected behavior. I'm developing a new client at the moment which will take over Mopify and will support all type of sources, but for now it only supports your Spotify tracks.

**Comment by ronilaukkarinen** [comment]
Ok.
Here's the output after pressing play two times. No output before clicking the play button.

````
Potentially unhandled rejection [1] TypeError: Cannot read property 'uri' of undefined
    at http://192.168.2.100:6680/mopify/src/app/services/mopidy.service.js:186:30
    at tryCatchReject (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:2221:30)
    at runContinuation1 (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:2180:4)
    at Fulfilled.19.Fulfilled.when (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:1968:4)
    at Pending.19.Pending.run (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:1859:13)
    at Scheduler.5.Scheduler._drain (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:330:19)
    at 5.async.drain (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:295:9)
    at http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:208:21(anonymous function) @ mopidy.js:1135report @ mopidy.js:1162flush @ mopidy.js:1184
mopidy.js:1135 Potentially unhandled rejection [2] TypeError: Cannot read property 'uri' of undefined
    at http://192.168.2.100:6680/mopify/src/app/services/mopidy.service.js:186:30
    at tryCatchReject (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:2221:30)
    at runContinuation1 (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:2180:4)
    at Fulfilled.19.Fulfilled.when (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:1968:4)
    at Pending.19.Pending.run (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:1859:13)
    at Scheduler.5.Scheduler._drain (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:330:19)
    at 5.async.drain (http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:295:9)
    at http://192.168.2.100:6680/mopify/src/vendor/mopidy/mopidy.js:208:21(anonymous function) @ mopidy.js:1135report @ mopidy.js:1162flush @ mopidy.js:1184
api.spotify.com/v1/me/tracks?limit=50&offset=850:1 GET https://api.spotify.com/v1/me/tracks?limit=50&offset=850 502 (Bad Gateway)
error.service.js:6 TypeError: Cannot read property 'id' of undefined
    at albums.controller.js:68
    at processQueue (angular.js:13189)
    at angular.js:13205
    at Scope.promises.$get.Scope.$eval (angular.js:14401)
    at Scope.promises.$get.Scope.$digest (angular.js:14217)
    at Scope.promises.$get.Scope.$apply (angular.js:14506)
    at done (angular.js:9659)
    at completeRequest (angular.js:9849)
    at XMLHttpRequest.requestLoaded (angular.js:9790)
```

**Comment by ronilaukkarinen** [comment]
Maybe related to my question [here](https://discuss.mopidy.com/t/no-audio-in-http-web-clients/864), so I'm closing this for now. Thanks for the answers.

**Comment by dirkgroenen** [comment]
No problem, you're welcome.
