### ISSUE TITLE
Broken instalation

### ISSUE THREAD

**Issue by nicoworq** [dirkgroenen/mopidy-mopify#185]
Hi ! Great application ! 

Everything was ok since today. Can't connect via web browser. 

When i run mopidy i get this : 

`pi@raspberrypi ~ $ mopidy
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==2.0.0', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy/__main__.py", line 8, in <module>
    from mopidy.internal.gi import Gst  # noqa: Import to initialize
  File "/usr/local/lib/python2.7/dist-packages/mopidy/internal/gi.py", line 9, in <module>
    gi.require_version('Gst', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 73, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
`

Try to update, and reinstall but the error it's the same . 
What i should do ? 
Thanks !

**Comment by dirkgroenen** [comment]
Well first you should open this issue in the mopidy repo instead of mopify ;) But to give a more helpful  answer: it looks to me like your installation has some trouble finding gstreamer. You sure you've installed the correct one?

**Comment by nicoworq** [comment]
Ups ! My bad ! 

Yes. It was working fine until today. I'll see what may have happened with gstreamer. 

Thanks  !

**Comment by kingosticks** [comment]
Mopidy v2.0 requires Gstreamer 1.0, which you seem not to have. As always, installation instructions (complete with the list of required dependencies) are available in the Mopidy documentation.

You should install and update Mopidy through your package manager to avoid problems like this. Or be sure sure to read the changelog when updating Mopidy.

**Comment by dirkgroenen** [comment]
No problem. Mopidy 2.0 requires gstreamer 1.0, so you might want to check that out.
