### ISSUE TITLE
Playlists not loading

### ISSUE THREAD

**Issue by jimrollenhagen** [dirkgroenen/mopidy-mopify#196]
Running latest from pip, I get this error loading any playlist:

```
May 06 08:38:15 hipderp mopidy[22439]: ERROR    SpotifyBackend backend caused an exception.
May 06 08:38:15 hipderp mopidy[22439]: Traceback (most recent call last):
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_e
May 06 08:38:15 hipderp mopidy[22439]:     yield
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 236, in lookup
May 06 08:38:15 hipderp mopidy[22439]:     result = future.get()
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
May 06 08:38:15 hipderp mopidy[22439]:     compat.reraise(*self._data['exc_info'])
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
May 06 08:38:15 hipderp mopidy[22439]:     exec('raise tp, value, tb')
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
May 06 08:38:15 hipderp mopidy[22439]:     response = self._handle_receive(message)
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
May 06 08:38:15 hipderp mopidy[22439]:     return callee(*message['args'], **message['kwargs'])
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/mopidy_spotify/library.py", line 38, in lookup
May 06 08:38:15 hipderp mopidy[22439]:     return lookup.lookup(self._config, self._backend._session, uri)
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/mopidy_spotify/lookup.py", line 33, in lookup
May 06 08:38:15 hipderp mopidy[22439]:     return list(_lookup_playlist(config, sp_link))
May 06 08:38:15 hipderp mopidy[22439]:   File "/usr/lib/python2.7/site-packages/mopidy_spotify/lookup.py", line 95, in _lookup_
May 06 08:38:15 hipderp mopidy[22439]:     sp_playlist.load()
May 06 08:38:15 hipderp mopidy[22439]: AttributeError: 'NoneType' object has no attribute 'load'
```

Mopidy is installed from AUR:
```
$ mopidy --version
Mopidy 2.0.0
```

Mopify installed from pip:
```
$ pip freeze | grep Mopify
Mopidy-Mopify==1.5.17
```

I also get errors loading albums. e.g. searching "kendrick", navigating to kendrick lamar artist page, and clicking an album:
```
May 06 08:40:26 hipderp mopidy[22439]: INFO     Searching Spotify for: "kendrick"
May 06 08:40:26 hipderp mopidy[22439]: INFO     Spotify search aborted: Spotify is offline
May 06 08:40:30 hipderp mopidy[22439]: INFO     Failed to lookup "spotify:album:5WSPnYTQ6YZ1UvBRi5quhO": Session must be logged
```

My local internet seems fine, despite the "Spotify is offline" error.

Any thoughts?

**Comment by dirkgroenen** [comment]
I've got no idea, but I do know this has nothing to do with Mopify. I think you'd be better off opening this issue in Mopidy-Spotify since it's clearly a backend issue. ;)
