### ISSUE TITLE
Nothing gets added to queue / played

### ISSUE THREAD

**Issue by devdavidkarlsson** [dirkgroenen/mopidy-mopify#197]
Mopify appears to start sucessfully, however no songs appear to start, just the slider counting seconds, also nothing gets added to queue. Tried both right click add to queue and play and clicking play directly. (Playing a m3u radio works through moped)

This is the logg i found:

```
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf --save-debug-log" as user mopidy
INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /etc/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, mpd, http, file, stream, spotmop, m3u, softwaremixer, moped, party, websettings, local
INFO     Disabled extensions: none
INFO     Starting Spotmop web client 2.6.5
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Mixer volume set to 80
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Audio output set to "alsasink buffer-time=300000 latency-time=20000"
INFO     No local library metadata cache found at /var/lib/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: QueueManagerFrontend, MpdFrontend, HttpFrontend
INFO     MPD server running at [::]:6600
INFO     HTTP server running at [::]:6680
INFO     Starting GLib mainloop
INFO     Pusher server running on []:6681
ERROR    Uncaught exception in /mopify/queuemanager/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 316, in wrapper
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_mopify/services/queuemanager/requesthandler.py", line 37, in on_message
    call = getattr(mem.queuemanager, data['method'])(**args)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_mopify/services/queuemanager/core.py", line 33, in add_play_next
    self.queue.insert(0, tracks[0])
IndexError: list index out of range
```

**Comment by dirkgroenen** [comment]
Is this still an issue?

**Comment by devdavidkarlsson** [comment]
Yes this is still an issue for me.

**Comment by BuurtBuzz** [comment]
Same here. Is this project still alive?
