### ISSUE TITLE
Unexpected response received.

### ISSUE THREAD

**Issue by srodrig0209** [dirkgroenen/mopidy-mopify#88]
Just upgraded to

Mopidy (1.0.0)
Mopidy-Mopify (1.4.1)
Mopidy-Spotify(1.3.0)

and now I'm getting the following in the console when I attempt to play a song. Anyone else seeing this?

![screen shot 2015-04-06 at 4 39 18 pm](https://cloud.githubusercontent.com/assets/2318521/7011985/cd9bf3fa-dc7b-11e4-9782-f5b32f2d1b7b.png)
![screen shot 2015-04-06 at 4 44 13 pm](https://cloud.githubusercontent.com/assets/2318521/7012048/3a2f184e-dc7c-11e4-9f94-83fa6c61b123.png)

Here's the text under `traceback`

```"Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mopidy/utils/jsonrpc.py", line 132, in _handle_single_request
    result = self._unwrap_result(result)
  File "/usr/local/lib/python2.7/site-packages/mopidy/utils/jsonrpc.py", line 221, in _unwrap_result
    result = result.get()
  File "/usr/local/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/mopidy/core/playback.py", line 277, in play
    self._play(tl_track, on_error_step=1)
  File "/usr/local/lib/python2.7/site-packages/mopidy/core/playback.py", line 310, in _play
    backend.playback.prepare_change()
  File "/usr/local/lib/python2.7/site-packages/pykka/proxy.py", line 161, in __getattr__
    raise AttributeError('%s has no attribute "%s"' % (self, name))
AttributeError: <ActorProxy for SpotifyBackend (urn:uuid:f0a679e4-9d39-48e8-a8b5-691a10be42de), attr_path=('playback',)> has no attribute "prepare_change"
"````

**Comment by dirkgroenen** [comment]
Hmm looks more like an issue on mopidy-spotify's side. Might worth opening an issue in their repo?

**Comment by jodal** [comment]
There's no interesting changes in Mopidy-Spotify since forever.

The info on the screenshot doesn't help much. You may expand all the nodes
in the browser console to get to the actual error.

**Comment by srodrig0209** [comment]
I'll remove all packages and attempt a clean install then. Mopidy -> Mopidy-Spotify -> Mopidy-Mopify and pray haha. I had a bunch of issues when attempting an upgrade where I had to `brew link` several times just to get Mopidy-Spotify to the latest version.

**Comment by srodrig0209** [comment]
Can't reproduce, but it appears to be working fine now.
